spring:
    application:
        name: item-service
    cloud:
        config:
            override-none: true

server:
    port: 8001

eureka:
    client:
        service-url:
            defaultZone: http://localhost:2001/eureka

